AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  generate-s3-presigned-java

  Sample SAM Template for generate-s3-presigned-java

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Parameters:
  S3BucketName:
    Type: String
    Default: s3-presigned-bucket-demo
    Description: S3 Bucket Name

Globals:
  Function:
    Timeout: 20
    MemorySize: 512

    # You can add LoggingConfig parameters such as the Logformat, Log Group, and SystemLogLevel or ApplicationLogLevel. Learn more here https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html#sam-function-loggingconfig.
    LoggingConfig:
      LogFormat: JSON
Resources:
  # S3 Bucket with acceleration turned on
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      AccelerateConfiguration:
        AccelerationStatus: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        - Key: Name
          Value: !Ref S3BucketName

  GenerateUrlFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: GenerateUrlFunction
      Handler: GenerateUrl.App::handleRequest
      Runtime: java21
      Architectures:
      - x86_64
      MemorySize: 512
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          BUCKET_NAME: !Ref S3Bucket
      Events:
        GenerateUrl:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /upload
            Method: post
            RestApiId: !Ref GenerateUrlApi
      Policies:
        - S3WritePolicy:
            BucketName: !Ref S3Bucket

  #API with Lambda no proxy integration
  GenerateUrlApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      EndpointConfiguration: REGIONAL
      Auth:
        DefaultAuthorizer: AWS_IAM

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  GenerateUrlApi:
    Description: API Gateway endpoint URL for Prod stage for Generate Url function
    Value: !Sub "https://${GenerateUrlApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/upload/"
  GenerateUrlFunction:
    Description: Generate Url Lambda Function ARN
    Value: !GetAtt GenerateUrlFunction.Arn
  GenerateUrlFunctionIamRole:
    Description: Implicit IAM Role created for Generate Url function
    Value: !GetAtt GenerateUrlFunctionRole.Arn
